image: cirrusci/flutter:2.2.3

stages:
  - test
  - e2e-test

app-test:
  stage: test
  script:
    - flutter --version
    - cd teamapp_frontend
    - flutter pub get
    - flutter test 
  interruptible: true

app-e2e-test:
  stage: e2e-test
  script:
    - cd teamapp_frontend/test_driver
    - dart ./app_test.dart
  interruptible: true
  