image: cirrusci/flutter:2.2.3

.prepare_step:
  before_script:
    - echo no | avdmanager create avd --force -n test -k "system-images;android-29;default;armeabi-v7a"
    - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window
    - adb wait-for-device
    - adb shell input keyevent 82
    - ./gradlew check connectedCheck

stages:
  - test
  - e2e-test

# app-test:
#   stage: test
#   script:
#     - flutter --version
#     - cd teamapp_frontend
#     - flutter pub get
#     - flutter test 
#   interruptible: true

app-e2e-test:
  image: cirrusci/android-sdk:29
  stage: e2e-test
  extends: .prepare_step
  script:
    - cd teamapp_frontend
    - flutter pub get
    - cd test_driver
    - dart ./app_test.dart
  interruptible: true
  