image: cirrusci/flutter:2.2.3

stages:
  - test

app-test:
  stage: test
  only:
    - merge_requests
  script:
    - flutter --version
    - cd team_app_frontend
    - flutter pub get
    - flutter test 
  interruptible: true