image: cirrusci/flutter:2.8.1

stages:
  - test
  - e2e-test

app-test:
  stage: test
  when: manual
  script:
    - flutter --version
    - cd teamapp_frontend
    - flutter pub get
    - flutter test 
  interruptible: true

app-e2e-test:
  stage: e2e-test
  when: manual
  script:
    - wget --quiet --output-document=android-wait-for-emulator https://raw.githubusercontent.com/travis-ci/travis-cookbooks/0f497eb71291b52a703143c5cd63a217c8766dc9/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
    - chmod +x android-wait-for-emulator
    - sdkmanager --install "system-images;android-24;default;armeabi-v7a" > install.log
    - avdmanager list avd
    - echo no | avdmanager create avd -n test -k "system-images;android-24;default;armeabi-v7a"
    - emulator -avd test -no-window -no-audio &
    - ./android-wait-for-emulator
    - adb shell input keyevent 82

    - cd teamapp_frontend
    - flutter pub get
    - flutter doctor
    - cd test_driver
    - dart ./app_test.dart
  interruptible: true
