image: cirrusci/flutter:2.10.3

stages:
  - build
  - integration-test

android-build:
  stage: build
  before_script:
    - cd mobile
  script:
    - flutter pub get
    - cd android
    - flutter build apk
    - ./gradlew app:assembleAndroidTest
    - ./gradlew app:assembleDebug -Ptarget="integration_test/main_test.dart"
  artifacts:
    paths:
      - mobile/build/app/outputs/

backend-build:
  image: docker
  services:
        - docker:dind
  stage: build
  before_script:
    - cd backend
  script: 
    - echo $DOCKER_PASSWORD | docker login registry.gitlab.com -u $DOCKER_USERNAME
    - docker build -t registry.gitlab.com/dkata/teamapp/backend:latest .
    - docker push registry.gitlab.com/dkata/teamapp/backend:latest

android-integration-test:
  stage: integration-test
  image: google/cloud-sdk
  before_script:
    - cd mobile
  script:
    - echo $SERVICE_ACCOUNT_KEY > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud config set project $PROJECT_ID
    - gcloud firebase test android models list
    - gcloud firebase test android run 
      --type instrumentation 
      --app build/app/outputs/apk/debug/app-debug.apk 
      --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk 
      --device model=Pixel3,version=30,locale=en,orientation=portrait
      --use-orchestrator
      --timeout 5m
  when: manual

.ios-build:
  stage: build
  before_script:
    - cd mobile
  script:
    - flutter pub get
    - cd ios
    - flutter build ios --release