# image: cirrusci/android-sdk:29
image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.3"
  SDK_TOOLS: "4333796"
  EMULATOR_VERSION: "24"
  
before_script:
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${SDK_TOOLS}.zip
  - unzip -q android-sdk.zip -d android-sdk-linux
  - rm android-sdk.zip

  - mkdir android-sdk-linux/licenses
  - printf "8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e" > android-sdk-linux/licenses/android-sdk-license
  - printf "84831b9409646a918e30573bab4c9c91346d8abd" > android-sdk-linux/licenses/android-sdk-preview-license
  - android-sdk-linux/tools/bin/sdkmanager --update > update.log
  - android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" "build-tools;${ANDROID_BUILD_TOOLS}" "extras;google;m2repository" "extras;android;m2repository" > installPlatform.log

  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/

# .prepare_step:
#   before_script:
#     - echo no | avdmanager create avd --force -n test -k "system-images;android-29;default;armeabi-v7a"
#     - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window
#     - adb wait-for-device
#     - adb shell input keyevent 82
#     - ./gradlew check connectedCheck

stages:
  # - test
  - e2e-test

# app-test:
#   stage: test
#   script:
#     - flutter --version
#     - cd teamapp_frontend
#     - flutter pub get
#     - flutter test 
#   interruptible: true

app-e2e-test:
  stage: e2e-test
  # extends: .prepare_step
  script:
    - apt-get --quiet update --yes
    - apt-get --quiet install --yes libx11-dev libpulse0 libgl1 libnss3 libxcomposite-dev libxcursor1 libasound2
    - wget --quiet --output-document=android-wait-for-emulator https://raw.githubusercontent.com/travis-ci/travis-cookbooks/0f497eb71291b52a703143c5cd63a217c8766dc9/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
    - chmod +x android-wait-for-emulator
    - android-sdk-linux/tools/bin/sdkmanager --update > update.log
    - android-sdk-linux/tools/bin/sdkmanager "platform-tools" "emulator" "system-images;android-${EMULATOR_VERSION};default;armeabi-v7a"  > installEmulator.log
    - android-sdk-linux/tools/bin/sdkmanager --list
    - echo no | android-sdk-linux/tools/bin/avdmanager create avd -n test -k "system-images;android-${EMULATOR_VERSION};default;armeabi-v7a"
    - android-sdk-linux/emulator/emulator -avd test -no-window -no-audio &
    - ./android-wait-for-emulator
    - adb shell input keyevent 82
    - cd teamapp_frontend
    - flutter pub get
    - cd test_driver
    - dart ./app_test.dart
  interruptible: true
  