image: cirrusci/flutter:2.8.1
# image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "30"
  ANDROID_BUILD_TOOLS: "30.0.2"
  SDK_TOOLS: "7583922" # from https://developer.android.com/studio/#command-tools
  EMULATOR_VERSION: "24"

# .prepare_step:
#   before_script:
#     - echo no | avdmanager create avd --force -n test -k "system-images;android-29;default;armeabi-v7a"
#     - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window
#     - adb wait-for-device
#     - adb shell input keyevent 82

stages:
  # - test
  - e2e-test

# app-test:
#   stage: test
#   script:
#     - flutter --version
#     - cd teamapp_frontend
#     - flutter pub get
#     - flutter test 
#   interruptible: true

app-e2e-test:
  stage: e2e-test
  script:
    # - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${SDK_TOOLS}.zip
    # - unzip -q android-sdk.zip -d android-sdk-linux
    # - rm android-sdk.zip

    # - android-sdk-linux/tools/bin/sdkmanager --update > update.log
    # - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" "build-tools;${ANDROID_BUILD_TOOLS}" "extras;google;m2repository" "extras;android;m2repository" > installPlatform.log

    # - export ANDROID_HOME=$PWD/android-sdk-linux
    # - export ANDROID_SDK_ROOT=$PWD/android-sdk-linux
    # - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/

    # - apt-get --quiet update --yes
    # - apt-get --quiet install --yes libx11-dev libpulse0 libgl1 libnss3 libxcomposite-dev libxcursor1 libasound2
    - wget --quiet --output-document=android-wait-for-emulator https://raw.githubusercontent.com/travis-ci/travis-cookbooks/0f497eb71291b52a703143c5cd63a217c8766dc9/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
    - chmod +x android-wait-for-emulator
    
    - echo y | sdkmanager --install "platform-tools" "emulator" "system-images;android-${EMULATOR_VERSION};default;armeabi-v7a"
    - echo no | $ANDROID_HOME/tools/bin/avdmanager create avd -n test -k "system-images;android-${EMULATOR_VERSION};default;armeabi-v7a"
    - $ANDROID_HOME/emulator/emulator -avd test -no-window -no-audio & ./android-wait-for-emulator
    - adb shell input keyevent 82

    - cd teamapp_frontend
    - flutter pub get
    - cd test_driver
    - dart ./app_test.dart
  interruptible: true
  
# flutter-app-e2e-test:
#   stage: e2e-test
#   when: manual
#   image: cirrusci/flutter:2.8.1
#   script:
#     - cd teamapp_frontend
#     - flutter doctor
    
