image: cirrusci/flutter:2.8.1

stages:
  - test
  - e2e-test

app-test:
  stage: test
  script:
    - flutter --version
    - cd teamapp_frontend
    - flutter pub get
    - flutter test 
  interruptible: true

app-e2e-test:
  stage: e2e-test
  script:
    - sdkmanager --install "platform-tools" "emulator" "system-images;android-29;default;armeabi-v7a" > install.log
    - echo no | avdmanager create avd -n test -k "system-images;android-29;default;armeabi-v7a"
    - emulator -avd test -no-window -no-audio &
    - adb wait-for-device
    - adb shell input keyevent 82

    - cd teamapp_frontend
    - flutter pub get
    - cd test_driver
    - dart ./app_test.dart
  interruptible: true
