image: cirrusci/flutter:2.10.3

stages:
  - test
  - build
  - integration-test
  - deploy

local-test:
  stage: test
  tags:
    - 'mobile'
  script:
    - cd mobile
    - flutter pub get
    - firebase emulators:exec --import './integration_test/firebase_emulator' 'flutter test integration_test/main_test.dart'

backend-build:
  extends: .backend-changes
  image: gcr.io/kaniko-project/executor:debug
  stage: build
  before_script:
    - cd backend
  script: 
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/backend:latest"

android-build:
  extends: .mobile-changes
  tags:
    - 'mobile'
  stage: build
  before_script:
    - cd mobile
  script:
    - flutter pub get
    - cd android
    - flutter build apk
    - ./gradlew app:assembleAndroidTest
    - ./gradlew app:assembleDebug -Ptarget="integration_test/main_test.dart"

backend-deploy:
  extends: .backend-changes
  image:
    name: bitnami/kubectl:latest
  stage: deploy
  needs:
    - backend-build
  before_script:
    - cp $KUBERNETES_CONFIG $HOME/.kube/config
    - cd backend
  script: 
    - kubectl apply -f deploy/production.yaml
    - kubectl rollout restart deployment backend -n teamapp

android-deploy:
  extends: .mobile-changes
  tags:
    - 'mobile'
  stage: deploy
  needs:
    - android-build
  before_script:
    - cd mobile
  script:
    - firebase appdistribution:distribute ./build/app/outputs/flutter-apk/app-release.apk
      --groups users
      --app 1:302449687825:android:7bb3ac61443781e5cd20b0
      --token $FIREBASE_TOKEN

android-integration-test:
  extends: .mobile-changes
  tags:
    - 'mobile'
  stage: integration-test
  image: google/cloud-sdk
  needs:
    - android-build
  before_script:
    - cd mobile
  script:
    - echo $SERVICE_ACCOUNT_KEY > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud config set project $PROJECT_ID
    - gcloud firebase test android models list
    - gcloud firebase test android run 
      --type instrumentation 
      --app build/app/outputs/apk/debug/app-debug.apk 
      --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk 
      --device model=Pixel3,version=30,locale=en,orientation=portrait
      --use-orchestrator
      --timeout 5m
  when: manual

.root-changes:
  only:
    changes:
      - .gitlab-ci.yml


.backend-changes:
  extends: .root-changes
  only:
    changes:
      - backend/*
      - backend/**/*

.mobile-changes:
  extends: .root-changes
  only:
    changes:
      - mobile/*
      - mobile/**/*