apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: teamapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: registry.gitlab.com/dkata/teamapp/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: docker
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: teamapp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31240
  selector:
    app: backend
