targets:
  $default:
    sources:
      - integration_test/**   # By default, build runner will not generate code in the integration folder
      - test/**               # so we override paths for code generation here
      - lib/**
      - $package$
    builders:
      bdd_widget_test|featureBuilder:
        options:
          stepFolderName: ../../step