name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.7.0
          cache: npm
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.10.3
          channel: stable
          cache: true
      - name: Install NPM Dependencies
        run: npm ci
      - name: Build Android
        run: |
          npx nx run mobile:buildApk
      - name: Check Android APK Existence
        id: android_apk
        uses: andstor/file-existence-action@v1
        with:
          files: "apps/mobile/build/app/outputs/apk/release/app-release.apk"
      - name: Upload APK to Firebase App Distribution
        if: steps.android_apk.files_exists == 'true'
        run: |
          npx firebase-tools appdistribution:distribute apps/mobile/build/app/outputs/apk/release/app-release.apk \
            --groups users \
            --app ${{secrets.FIREBASE_APP_ID}} \
            --token ${{secrets.FIREBASE_TOKEN}}
