name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: 'stable'
      - run: 'npm ci'
      - name: Build Android
        uses: MansaGroup/nrwl-nx-action@v2
        with:
          targets: buildApk
          projects: mobile
          nxCloud: true
