name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android:
    runs-on: macos-latest
    steps:
      - name: Build Android
        uses: MansaGroup/nrwl-nx-action@v2
        with:
          targets: buildApk
          projects: mobile
          nxCloud: true
