name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.7.0
          cache: 'npm'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: 'stable'
          cache: true
      - name: Build Android
        run: 'npx nx run mobile:buildApk'
      - name: Upload APK to Firebase App Distribution
        run: |
          ls apps/mobile
          ls apps/mobile/build/app/outputs/
          ls apps/mobile/build/app/outputs/apk/release/
          ls apps/mobile/build/app/outputs/flutter-apk/
          npx firebase-tools appdistribution:distribute apps/mobile/build/app/outputs/apk/release/app-release.apk \
            --groups users \
            --app ${{secrets.FIREBASE_APP_ID}} \
            --token ${{secrets.FIREBASE_TOKEN}}
