name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android:
    name: Build Android
    uses: MansaGroup/nrwl-nx-action@v2
    with:
      target: buildApk
      projects: mobile
      nxCloud: true
